name: files
description: dahliaOS Files.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.16.0

  ffi: ^2.0.1
  filesize: ^2.0.1
  flutter:
    sdk: flutter

  handy_window: ^0.4.0
  intl: any
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2

  material_design_icons_flutter: ^7.0.7296 
  mime: ^2.0.0

  pasteboard: ^0.3.0
  path: ^1.8.2
  path_provider: ^2.0.2
  provider: ^6.0.0

  recase: ^4.1.0
  super_clipboard: ^0.8.24
  ubuntu_service: ^0.4.0
  udisks:
    git: https://github.com/HrX03/udisks.dart
  url_launcher: any
  windows_path_provider:
    git:
      url: https://github.com/HrX03/windows_path_provider.git
  xdg_directories: ^1.0.0
  yaru: ^5.3.1

dev_dependencies:
  build_runner: ^2.3.2
  isar_generator: ^3.0.2
  lint: ^2.1.1

flutter:
  uses-material-design: true
